name: Lua TidesDB CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout tidesdb-lua repo
      uses: actions/checkout@v4
      with:
        repository: tidesdb/tidesdb-lua
        path: tidesdb-lua

    - name: Checkout tidesdb repo
      uses: actions/checkout@v4
      with:
        repository: tidesdb/tidesdb
        path: tidesdb

    - name: Install libzstd-dev,liblz4-dev and libsnappy-dev
      run: |
        sudo apt update
        sudo apt install -y libzstd-dev liblz4-dev libsnappy-dev

    - name: configure cmake build for tidesdb
      run: |
        cd tidesdb
        cmake -DTIDESDB_WITH_SANITIZER=OFF --debug-output  -S . -B build && make -C build/
        sudo cmake --install build
        sudo ldconfig


    - name: Install Lua and Lua development files
      run: |
        sudo apt update
        sudo apt install -y lua5.3 liblua5.3-dev lua-busted

    - name: configure cmake build
      run: |
        cd tidesdb-lua
        cmake --debug-output  -S . -B build && make -C build/

    - name: Run Busted
      run: |
        cd tidesdb-lua
        busted .
    

    - name: run lua tests
      run: |
        cd tidesdb-lua/build
        lua ../test_lua.lua

