name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout tidesdb repo
      uses: actions/checkout@v4
      with:
        repository: https://github.com/tidesdb/tidesdb-lua.git
        path: tidesdb
    - name: configure cmake build
      run: ./cmake -S . -B build
    - name: make
      run: cd build && make
    - name: run lua tests
      run: lua ../test_lua.lua
